version: '3.8'
services:
  jenkins:
    image: jenkins/jenkins:lts
    restart: always
    environment:
     - TZ=Asia/Taipei
    privileged: true
    user: root
    ports:
     - 8099:8080
     - 50000:50000
    container_name: jenkins
    volumes:
      # Without /bin/tini, it can not be brought so comment out the below line
      #- ./data/usr:/usr
      - /data/shell:/data/shell
      - ./data/jenkins_configuration:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp:/tmp
