version: "3.8"
services:
  jenkins:
    image: jenkins/jenkins:lts
    restart: always
    environment:
      - TZ=Asia/Taipei
    privileged: true
    user: root
    ports:
      - 8099:8080
      - 50000:50000
    container_name: jenkins
    volumes:
      - /data/shell:/data/shell
      - ./data/jenkins_configuration:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp:/tmp
    command: >
      # try to use tsinghua mirror for solving the network problem
      /bin/bash -c "sed -i 's|http://deb.debian.org/debian%7Chttp://mirrors.tuna.tsinghua.edu.cn/debian%7Cg' /etc/apt/sources.list &&
      apt-get update &&
      apt-get install -y curl dnsutils &&
      /usr/local/bin/jenkins.sh"
